services:
  server:
    image: ghcr.io/tinglesoftware/dependabot:${IMAGE_TAG:-latest}
    ports: [8080:8080]
    restart: unless-stopped
    user: root # required to write to the mounted volumes
    environment:
      GITHUB_SHA: '${GITHUB_SHA:-unknown}'
      GITHUB_REF_NAME: '${GITHUB_REF_NAME:-unknown}'

      EFCORE_PERFORM_MIGRATIONS: 'true' # Perform migrations on startup
      # InitialSetup__Projects: '[{"url":"https://dev.azure.com/tingle/dependabot","token":"dummy","AutoComplete":true, "GithubToken":"${GITHUB_TOKEN}"}]'
      ConnectionStrings__Sqlite: 'Data Source=mnt/dependabot/db/database.db'
      DistributedLocking__FilePath: '/mnt/dependabot/locks'
      Workflow__JobsApiUrl: 'http://server/'
      Workflow__ArtifactsDirectory: '/mnt/dependabot/artifacts'
      Workflow__CertsDirectory: '/mnt/dependabot/certs'
      Workflow__ProxyDirectory: '/mnt/dependabot/proxy'
      Workflow__JobsDirectory: '/mnt/dependabot/jobs'
      # Workflow__ProxyImageTag: '${DEPENDABOT_PROXY_IMAGE_TAG}'
      # Workflow__UpdaterImageTag: '${DEPENDABOT_UPDATER_IMAGE_TAG}'
      # EventBus__SelectedTransport: 'InMemory'
      Logging__OpenTelemetry__LogLevel__Default: Warning # only send warnings and above to OpenTelemetry
      Logging__LogLevel__Polly: None # too many logs
      Logging__OpenTelemetry__LogLevel__Polly: None # too many logs (one above seems not sufficient)
      Logging__LogLevel__Microsoft.AspNetCore.DataProtection.KeyManagement.XmlKeyManager: Error
    volumes:
      - db:/mnt/dependabot/db
      - artifacts:/mnt/dependabot/artifacts
      - certs:/mnt/dependabot/certs
      - locks:/mnt/dependabot/locks
      - proxy:/mnt/dependabot/proxy
      - jobs:/mnt/dependabot/jobs
      - /var/run/docker.sock:/var/run/docker.sock # Allows the container to create/manage other containers

volumes:
  db:
  artifacts:
  certs:
  locks:
  proxy:
  jobs:
