name: Changeset

on:
  workflow_dispatch:
  push:
    branches: [main]

permissions:
  contents: write # write required to create a PR

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  Changeset:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup pnpm
        uses: pnpm/action-setup@v4

      - name: Setup node
        uses: actions/setup-node@v4
        with:
          node-version: 22
          cache: pnpm

      - name: Download deps
        run: pnpm install

      - name: Create release pull request
        uses: changesets/action@v1
        with:
          title: 'Version packages'
          version: pnpm packages:version
          commit: 'Version packages'
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
