name: Cleanup

on:
  workflow_dispatch:
  schedule:
    - cron: '0 0 */14 * *' # every 14 days

permissions:
  packages: write

jobs:
  cleanup-server:
    runs-on: ubuntu-latest

    steps:
      - name: Delete old dependabot-server images
        uses: actions/delete-package-versions@v5
        with:
          package-name: 'dependabot-server'
          package-type: 'container'
          min-versions-to-keep: 20
          # exclude major and minor versions as per SemVer e.g. 1.20
          ignore-versions: '^([0-9]\\d*)\\.([0-9]\\d*)$'
