name: CLI

on:
  workflow_dispatch:
  push:
    branches: [main]
    paths:
      - 'packages/cli/**'
      - 'packages/core/**'
      - 'packages/runner/**'
      - '.github/workflows/cli.yml'
  pull_request:
    branches: [main]
    paths:
      - 'packages/cli/**'
      - 'packages/core/**'
      - 'packages/runner/**'
      - '.github/workflows/cli.yml'

permissions:
  contents: read

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

env:
  NEXT_TELEMETRY_DISABLED: 1 # Disable Next.js telemetry
  TURBO_TELEMETRY_DISABLED: 1 # Disable Turbo telemetry

jobs:
  CLI:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v5
        with:
          submodules: true

      - name: Setup pnpm
        uses: pnpm/action-setup@v4

      - name: Setup node
        uses: actions/setup-node@v6
        with:
          node-version: 22
          cache: 'pnpm'

      - name: Setup turborepo caching
        uses: rharkor/caching-for-turbo@v2.3.2

      - name: Download deps
        run: pnpm install
        working-directory: '${{ github.workspace }}/packages/cli'

      - name: Build
        run: pnpm turbo build
        working-directory: '${{ github.workspace }}/packages/cli'

      - name: Lint
        run: pnpm turbo lint
        working-directory: '${{ github.workspace }}/packages/cli'

      - name: Test
        run: pnpm turbo test
        working-directory: '${{ github.workspace }}/packages/cli'
