name: Extension

on:
  push:
    branches:
      - main
    tags:
      - '*'
    paths:
      - 'extension/**'
      - '.github/workflows/extension.yml'
      - '!extension/README.md'
      - '!docs/**'
  pull_request:
    branches:
      # Only trigger for PRs against `main` branch.
      - main
    paths:
      - 'extension/**'
      - '.github/workflows/extension.yml'
      - '!extension/README.md'
      - '!docs/**'

permissions:
  contents: write # write required for ncipollo/release-action to create a release
  attestations: write # required for actions/attest-build-provenance
  id-token: write # required for actions/attest-build-provenance

jobs:
  Build:
    runs-on: ubuntu-latest

    concurrency:
      group: ${{ github.workflow }}-${{ github.ref }}
      cancel-in-progress: true

    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0 # Required for GitVersion

      - name: Setup .NET SDK
        uses: actions/setup-dotnet@v4

      - name: Install GitVersion
        uses: gittools/actions/gitversion/setup@v3
        with:
          versionSpec: '6.0.x'

      - name: Determine Version
        id: gitversion
        uses: gittools/actions/gitversion/execute@v3
        with:
          useConfigFile: true

      - name: Setup pnpm
        uses: pnpm/action-setup@v4

      - name: Setup node
        uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: pnpm

      - name: Download deps
        run: pnpm install

      - name: Format check
        run: pnpm format:check

      - name: Test
        run: pnpm test
        working-directory: '${{ github.workspace }}/extension'

      - name: Build
        run: pnpm build
        working-directory: '${{ github.workspace }}/extension'

      - name: Update version numbers in vss-extension.json overrides files
        uses: cschleiden/replace-tokens@v1
        with:
          files: '["${{ github.workspace }}/extension/overrides*.json"]'
        env:
          MAJOR_MINOR_PATCH: ${{ steps.gitversion.outputs.majorMinorPatch }}
          BUILD_NUMBER: ${{ github.run_number }}

      - name: Update minor and path versions in task.json
        run: |
          # Major versions are left out here because they are fixed in the task.json files.
          # The minor and patch versions are updated to make sure we keep recent changes deployed.
          echo "`jq '.version.Minor=${{ steps.gitversion.outputs.minor }}' extension/tasks/dependabotV2/task.json`" > extension/tasks/dependabotV2/task.json
          echo "`jq '.version.Patch=${{ github.run_number }}' extension/tasks/dependabotV2/task.json`" > extension/tasks/dependabotV2/task.json

      - name: Create Extension (dev)
        run: >
          pnpm tfx extension create
          --root extension
          --manifest-globs vss-extension.json
          --output-path ${{ github.workspace }}/drop/dev
          --json5
          --overrides-file ${{ github.workspace }}/extension/overrides.dev.json

      - name: Create Extension (prod)
        run: >
          pnpm tfx extension create
          --root extension
          --manifest-globs vss-extension.json
          --output-path ${{ github.workspace }}/drop/prod
          --json5
          --overrides-file ${{ github.workspace }}/extension/overrides.prod.json

      - name: Upload Artifact (drop)
        uses: actions/upload-artifact@v4
        with:
          path: ${{ github.workspace }}/drop/*
          name: drop

  Publish:
    runs-on: ubuntu-latest
    needs: [Build]

    concurrency:
      group: ${{ github.workflow }}-${{ github.ref }}
      cancel-in-progress: false # wait for previous runs to complete

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Download Artifact
        uses: actions/download-artifact@v4
        with:
          name: drop

      - name: Provenance Attestation
        if: startsWith(github.ref, 'refs/tags/')
        uses: actions/attest-build-provenance@v2
        with:
          subject-path: |
            ${{ github.workspace }}/prod/*.vsix
            ${{ github.workspace }}/dev/*.vsix

      - name: Upload Release
        if: startsWith(github.ref, 'refs/tags/')
        uses: ncipollo/release-action@v1
        with:
          artifacts: '${{ github.workspace }}/prod/*.vsix,${{ github.workspace }}/dev/*.vsix'
          token: ${{ secrets.GITHUB_TOKEN }}
          draft: true
          allowUpdates: true

      - name: Setup pnpm
        uses: pnpm/action-setup@v4

      - name: Setup node
        uses: actions/setup-node@v4
        with:
          node-version: 20

      - name: Publish to marketplace (dev)
        if: github.ref == 'refs/heads/main'
        run: >
          pnpm tfx extension publish
          --vsix ${{ github.workspace }}/dev/*.vsix
          --auth-type pat
          --token ${{ secrets.AZURE_DEVOPS_EXTENSION_TOKEN }}
          --share-with tingle rhyskoedijk

      - name: Publish to marketplace (prod)
        if: startsWith(github.ref, 'refs/tags/')
        run: >
          pnpm tfx extension publish
          --vsix ${{ github.workspace }}/prod/*.vsix
          --auth-type pat
          --token ${{ secrets.AZURE_DEVOPS_EXTENSION_TOKEN }}
